[build]
  command = "npm run build"
  publish = "dist"
  functions = "backend/netlify/functions"

[functions]
  # Incluimos las dependencias necesarias para que Netlify las empaquete
  node_bundler = "esbuild"
  external_node_modules = ["pg", "crypto-js", "serverless-http", "express", "cors", "body-parser", "multer", "dotenv"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *"
    Access-Control-Allow-Origin = "*"
